version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.production.local
    environment:
      POSTGRES_DB: tekstil_kumas
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    env_file:
      - .env.production.local
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  pgdata:
